services:
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./apps/postgres:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=admin
      - POSTGRES_DB=catering